export type Lang = 'en' | 'id';

export const copy = {
  en: {
    navLinks: [
      { label: 'About', href: '#about' },
      { label: 'Skills', href: '#skills' },
      { label: 'Projects', href: '#projects' },
      { label: 'Contact', href: '#contact' },
    ],
    heroLabel: 'PERSONAL PROFILE / 01',
    heroGreeting: "Hi, I'm Aria",
    heroRole: 'Informatics & Data Science Student',
    heroLocation: 'Surabaya, Indonesia',
    heroCopy: "Hi, I'm Aria, a student at the University of Surabaya currently exploring Data Science and Artificial Intelligence. I enjoy exploring technology and building things through code. Nice to meet you!",
    heroCTA: 'Contact Me',
    aboutLabel: 'ABOUT / 02',
    aboutHeading: ['Curious about data,', 'the boundaries of AI,', 'and the craft of code.'],
    aboutCopy: "I'm Aria Hansa Junior, an Informatics and Data Science student at the University of Surabaya. My interest lies at the intersection of technology and problem-solving — exploring how intelligent systems work, how data reveals patterns, and how thoughtful code turns ideas into reality.",
    aboutMeta: ['University of Surabaya', 'Data Science', 'Artificial Intelligence', 'Surabaya, Indonesia'],
    skillsLabel: 'SKILLS / 03',
    skillGroups: [
      { title: 'Languages', items: ['Python', 'JavaScript', 'PHP', 'SQL'] },
      { title: 'Frameworks', items: ['React', 'Laravel'] },
      { title: 'Database', items: ['MySQL'] },
      { title: 'Domain', items: ['Data Science', 'Artificial Intelligence'] },
    ],
    projectsLabel: 'SELECTED WORK / 04',
    projectBadge: 'Featured Project',
    projectDesc: 'IndoLens is an AI-powered Indonesian actor face-recognition system using Computer Vision.',
    projectCTA: 'View Project',
    projectTags: ['Laravel 11', 'PHP', 'Python', 'YOLOv8', 'FaceNet', 'PyTorch', 'OpenCV', 'MySQL'],
    contactLabel: 'CONTACT / 05',
    contactHeading: "Let's Connect.",
    contactSub: "Whether you have a project in mind, a question, or just want to say hello — I'd love to hear from you.",
    address: 'Jl. Rungkut Mejoyo Selatan I No. 8, Rungkut, Surabaya, Jawa Timur 60293',
    footerCopy: '© 2024 Aria Hansa Junior',
    heroTypewriter: [
      'Building Intelligent Systems',
      'Exploring Data Patterns',
      'Crafting Clean Code'
    ],
  },
  id: {
    navLinks: [
      { label: 'Tentang', href: '#about' },
      { label: 'Keahlian', href: '#skills' },
      { label: 'Proyek', href: '#projects' },
      { label: 'Kontak', href: '#contact' },
    ],
    heroLabel: 'PROFIL PRIBADI / 01',
    heroGreeting: 'Halo, Saya Aria',
    heroRole: 'Mahasiswa Informatika & Ilmu Data',
    heroLocation: 'Surabaya, Indonesia',
    heroCopy: 'Halo, saya Aria, mahasiswa di Universitas Surabaya yang sedang mendalami Ilmu Data dan Kecerdasan Buatan. Saya senang menjelajahi teknologi dan membangun sesuatu melalui kode. Senang berkenalan dengan Anda!',
    heroCTA: 'Hubungi Saya',
    aboutLabel: 'TENTANG / 02',
    aboutHeading: ['Penasaran dengan data,', 'batas-batas AI,', 'dan seni menulis kode.'],
    aboutCopy: 'Saya Aria Hansa Junior, mahasiswa Informatika dan Ilmu Data di Universitas Surabaya. Minat saya berada di persimpangan teknologi dan pemecahan masalah — menjelajahi cara kerja sistem cerdas, bagaimana data mengungkap pola, dan bagaimana kode yang bijaksana mengubah ide menjadi kenyataan.',
    aboutMeta: ['Universitas Surabaya', 'Ilmu Data', 'Kecerdasan Buatan', 'Surabaya, Indonesia'],
    skillsLabel: 'KEAHLIAN / 03',
    skillGroups: [
      { title: 'Bahasa', items: ['Python', 'JavaScript', 'PHP', 'SQL'] },
      { title: 'Framework', items: ['React', 'Laravel'] },
      { title: 'Database', items: ['MySQL'] },
      { title: 'Domain', items: ['Ilmu Data', 'Kecerdasan Buatan'] },
    ],
    projectsLabel: 'KARYA PILIHAN / 04',
    projectBadge: 'Proyek Unggulan',
    projectDesc: 'IndoLens adalah sistem pengenalan wajah aktor Indonesia berbasis AI menggunakan Computer Vision.',
    projectCTA: 'Lihat Proyek',
    projectTags: ['Laravel 11', 'PHP', 'Python', 'YOLOv8', 'FaceNet', 'PyTorch', 'OpenCV', 'MySQL'],
    contactLabel: 'KONTAK / 05',
    contactHeading: 'Mari Terhubung.',
    contactSub: 'Apakah Anda memiliki proyek, pertanyaan, atau hanya ingin menyapa — saya senang mendengar dari Anda.',
    address: 'Jl. Rungkut Mejoyo Selatan I No. 8, Rungkut, Surabaya, Jawa Timur 60293',
    footerCopy: '© 2024 Aria Hansa Junior',
    heroTypewriter: [
      'Membangun Sistem Cerdas',
      'Mengeksplorasi Pola Data',
      'Merancang Kode yang Bersih'
    ],
  },
};
